language: java

front:
  - build
  - test

jobs:
  include:
    - stage: build
      env: Docker images build
      services:
        - docker
      script:
        # The front image includes a call to "grunt validate":
        - docker-compose -f docker-compose.yml build
    - stage: test
      env: Pre-commit checks
      script:
        # Installing pre-commit globally fails with:
        # Installing collected packages: aspy.yaml, cached-property, identify, nodeenv, pre-commit
        #   File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
        #     with open(dst, 'wb') as fdst:
        # IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/aspy.yaml-1.0.0-nspkg.pth'
        - pip install --user pre-commit && pre-commit run --all-files
    - stage: test
      env: Backend unit tests
      script:
        - cd vboard-ws
        - mvn test

cache:
  pip: true
  directories:
  - node_modules # npm packages
  - $HOME/.m2    # Maven packages
