application:
  name: vboard-ws
  version: DEV
  buildDate: 2019-10-29

aws-cognito:
  enabled: true
  jwt-http-header-name: X-AMZN-OIDC-DATA
  region: eu-west-1

logging:
  level:
    org.springframework.web: DEBUG
    com.vsct.vboard: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vboard_pins
    username: root
    password: root
elasticsearch:
  serverUri: http://localhost:9200

server:
  error:
    whitelabel:
      enabled: true
endpoints:
  enabled: true
  sensitive: false
management:
  security:
    enabled: false

com:
  vsct:
    vboard:
      hostname: localhost
uploads:
  imagesStorageDirectory: imagesStorageDir
  blogImagesDirectory: blogImagesDir
proxy:
  hostname:
emails:
  hostname: dummy
