spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vboard_pins
elasticsearch:
  serverUri: http://localhost:9200

server:
  error:
    whitelabel:
      enabled: true
endpoints:
  enabled: true
  sensitive: false
management:
  security:
    enabled: false

com:
  vsct:
    vboard:
      hostname: localhost
uploads:
  imagesStorageDirectory: imagesStorageDir
  blogImagesDirectory: blogImagesDir
proxy:
  hostname:
emails:
  hostname: dummy

keycloak:
  enabled: false
